### ISSUE TITLE
Test scene broken?

### ISSUE THREAD

**Issue by gl33mer** [keijiro/ParticleMotionVector#2]
Hey. Thanks for all your great work. 
Inspiring.

The test scene seems quite broken. missing scripts on the camera and postfx object , etc.

running on 2017.1 (latest)

**Comment by keijiro** [comment]
It uses submodule to import the post-processing stack. You can use `git submodule` commands to initialize it, or import the post-processing stack manually.

I'm closing this issue. Please feel free to reopen for further questions.
